export default [
  {
    id: "head",
    description: "head is the top part of the human body",
    active: false,
    shift: { x: 0, y: 2.8, z: 0.5 },
    direction: { x: 1.5, y: 1, z: 1 },
    label: "Head",
  },
  {
    id: "chest",
    description: "chest is chest chest is chestchest is chestchest is chest",
    active: false,
    shift: { x: 0, y: 1.4, z: 0.4 },
    direction: { x: 1, y: -0.5, z: 1 },
    label: "Chest",
  },
  {
    id: "back",
    description: "backbone is BBBBBBBBBBBBBBBBBBBB",
    active: false,
    shift: { x: 0, y: 1.5, z: -0.5 },
    direction: { x: 2, y: 1, z: -1.4 },
    label: "Backbone",
  },
  {
    id: "armR",
    description: "righ arm is useful",
    active: false,
    shift: { x: -1, y: 0.5, z: -0.12 },
    direction: { x: -2, y:-0.5, z: 1.5 },
    label: "Right Arm",
  },
  {
    id: "armL",
    description: "left arm is useful XD",
    active: false,
    shift: { x: 1, y: 0.5, z: -0.12 },
    direction: { x: 1, y: -1, z: 1.5 },
    label: "Left Arm",
  },
];
